### ISSUE TITLE
Feature request: placeholders in item names

### ISSUE THREAD

**Issue by SlimeDog** [games647/ScoreboardStats#193] opened 2017-04-12 14:38 UTC
Please support use of placeholders in item names to the left of the colon. For example:

>Scoreboard:
  ...
  Items:
  '&8%factions_faction%': '%factions_onlinemembers%'

**Comment by games647** [comment] 2017-09-21 16:37
Duplicate of #93

**Closed by games647** 2017-09-21 16:37 UTC
Labels: duplicate, enhancement
